### ISSUE TITLE
Enhancement: add overviews later

### ISSUE THREAD

**Issue by effjot** [hdus/pg_raster_upload#12]
Sometimes I import rasters without creating overviews, because it takes really long and I not always need them. But sometimes I’d like to add them later. Therefore I have extended the plugin with a dialog for adding overviews to an existing PostGIS raster layer.
If you’re interested, I could prepare a pull request.

**Comment by hdus** [comment]
Thank you very much for your efforts. I would very much like to have a look at your extension. Please prepare a pull request.
