### ISSUE TITLE
Close window after upload

### ISSUE THREAD

**Issue by pcav** [hdus/pg_raster_upload#2]
When upload is completed the popup window remains open. I'd suggest instead to print a "success" message and close it automatically.
Thanks, a much needed tool!

**Comment by hdus** [comment]
I find it better to leave the window open. If another raster is uploaded, it can be done immediately. The status bar also indicates whether the upload was successful. Does this contradict the QGIS specifications?

**Comment by pcav** [comment]
It makes sense to me, but IMHO it is not clear enough that the import was successful. See processing algs for examples.
BTW, why not converting the plugin into a processing alg?

Il 27 giugno 2021 20:13:59 CEST, hdus ***@***.***> ha scritto:
>I find it better to leave the window open. If another raster is
>uploaded, it can be done immediately. The status bar also indicates
>whether the upload was successful. Does this contradict the QGIS
>specifications?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hdus/pg_raster_upload/issues/2#issuecomment-869204614

-- 
Sorry for being short

**Comment by hdus** [comment]
See my comment in #3 https://github.com/hdus/pg_raster_upload/issues/3#issuecomment-869473389

**Comment by pcav** [comment]
quite clear, thanks @hdus
